# Generated by Django 3.2.9 on 2021-12-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApi', '0003_auto_20211205_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_id',
            new_name='id',
        ),
    ]
