# Generated by Django 3.2.9 on 2021-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.IntegerField(max_length=120)),
                ('restaurantId', models.IntegerField(max_length=120)),
                ('productId', models.IntegerField(max_length=120)),
                ('deliverymanId', models.IntegerField(max_length=120)),
                ('status', models.TextField()),
                ('dateOrder', models.DateField()),
                ('dateChangingStatus', models.DateField()),
            ],
        ),
    ]
