# Generated by Django 3.2.9 on 2021-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dateChangingStatus',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dateOrder',
            field=models.DateTimeField(),
        ),
    ]
