# Generated by Django 3.2.9 on 2021-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApi', '0002_auto_20211205_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(default=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
